Write a generic function that takes an integer n and generates the standard basis B for Rn as
a list of NumPy arrays.

In [3]:
import numpy as np

def generate_standard_basis(n):
    basis_vector = []
    for i in range(n):
        v = np.zeros(n)
        v[i]=1
        basis_vector.append(v)

    return basis_vector

In [4]:
n = 4
basis = generate_standard_basis(n)


In [5]:
basis

[array([1., 0., 0., 0.]),
 array([0., 1., 0., 0.]),
 array([0., 0., 1., 0.]),
 array([0., 0., 0., 1.])]

In [9]:
print("Problem 3 Result: ")

for i, b in enumerate(basis):
    print (f"e_{i+1} = {b}")

Problem 3 Result: 
e_1 = [1. 0. 0. 0.]
e_2 = [0. 1. 0. 0.]
e_3 = [0. 0. 1. 0.]
e_4 = [0. 0. 0. 1.]
